import dynamic from "next/dynamic";
import Head from "next/head";

const AboutUs = dynamic(() => import("@/components/pages/aboutUs"));

export default function HomePage() {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* Use relative path for the public directory image */}
        <link rel="icon" href="/rixingLogo.png" />
      </Head>
      <AboutUs />
    </>
  );
}
