import dynamic from "next/dynamic";
import Head from "next/head";

const ServicesPanCard = dynamic(
  () => import("@/components/pages/services/panCard")
);

export default function ServicesPanCardPage() {
  return (
    <>
      <Head>
        <title>Pan Card</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* Use relative path for the public directory image */}
        <link rel="icon" href="/rixingLogo.png" />
      </Head>

      <ServicesPanCard />
    </>
  );
}
