import dynamic from "next/dynamic";
import Head from "next/head";

const ServicesAeps = dynamic(() => import("@/components/pages/services/aeps"));

export default function ServicesAepsPage() {
  return (
    <>
      <Head>
        <title>AePS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* Use relative path for the public directory image */}
        <link rel="icon" href="/rixingLogo.png" />
      </Head>

      <ServicesAeps />
    </>
  );
}
