import dynamic from "next/dynamic";
import Head from "next/head";

const ServicesDmt = dynamic(() => import("@/components/pages/services/dmt"));

export default function ServicesDmtPage() {
  return (
    <>
      <Head>
        <title>Dmt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* Use relative path for the public directory image */}
        <link rel="icon" href="/rixingLogo.png" />
      </Head>
      <ServicesDmt />
    </>
  );
}
