import dynamic from "next/dynamic";
import Head from "next/head";

const Root = dynamic(() => import("@/components/pages/root"));

export default function RootPage() {
  return (
    <>
      <Head>
        <title>Rizing Pay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* Use relative path for the public directory image */}
        <link rel="icon" href="/rixingLogo.png" />
      </Head>

      <Root />
    </>
  );
}
