import dynamic from "next/dynamic";
import Head from "next/head";

const ServicesMatm = dynamic(() => import("@/components/pages/services/mAtm"));

export default function ServicesMatmPage() {
  return (
    <>
      <Head>
        <title>M Atm</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* Use relative path for the public directory image */}
        <link rel="icon" href="/rixingLogo.png" />
      </Head>
      <ServicesMatm />
    </>
  );
}
