import dynamic from "next/dynamic";
import Head from "next/head";

const ServicesUtilityuBills = dynamic(
  () => import("@/components/pages/services/utlitityBills")
);

export default function ServicesUtilityPage() {
  return (
    <>
      <Head>
        <title>Bill Payment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/rixingLogo.png" />
      </Head>
      <ServicesUtilityuBills />
    </>
  );
}
