"use client";
import dynamic from "next/dynamic";
import Head from "next/head";

const Agent = dynamic(() => import("@/components/pages/agent"));

export default function AgentPage() {
  return (
    <>
      <Head>
        <title>Become Agent</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* Use relative path for the public directory image */}
        <link rel="icon" href="/rixingLogo.png" />
      </Head>
      <Agent />
    </>
  );
}
